2023-04-14 09:50:13,929 ERROR: Exception on /login [GET] [in C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Macie\Desktop\Euromind\app\routes.py", line 122, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Macie\Desktop\Euromind\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Macie\Desktop\Euromind\app\templates\base.html", line 70, in top-level template code
    {% for message in messages %}
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block 'body'
    {% block scripts %}
  File "C:\Users\Macie\Desktop\Euromind\app\templates\base.html", line 49, in block 'scripts'
    {{ moment.include.moment() }}
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'type object' has no attribute 'include'
2023-04-14 09:51:04,271 ERROR: Exception on /login [GET] [in C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Macie\Desktop\Euromind\app\routes.py", line 122, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Macie\Desktop\Euromind\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Macie\Desktop\Euromind\app\templates\base.html", line 70, in top-level template code
    {% for message in messages %}
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block 'body'
    {% block scripts %}
  File "C:\Users\Macie\Desktop\Euromind\app\templates\base.html", line 49, in block 'scripts'
    {{ moment.include_moment() }}
  File "C:\Users\Macie\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'type object' has no attribute 'include'
2023-04-14 09:51:12,992 INFO: Microblog startup [in C:\Users\Macie\Desktop\Euromind\app\__init__.py:80]
